use peluqueria;

create table PAGOS (
		ID INT(7) NOT NULL AUTO_INCREMENT PRIMARY KEY,
		FECHA DATE NOT NULL,
		ID_CLIENTE INT(5),
		ID_TURNO INT (7),
		DESCRIPCION VARCHAR (140),
		IMPORTE DECIMAL(9,2),
		FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID) ON DELETE SET NULL
);