USE PELUQUERIA;

CREATE TABLE PERMISOS (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USER_ID VARCHAR(15) NOT NULL,
	MODULO VARCHAR(20) NOT NULL,
	MODULO_CREAR BOOL,
	MODULO_ELIMINAR BOOL,
	MODULO_MODIFICAR BOOL,
	MODULO_CONSULTAR BOOL,
	FOREIGN KEY(USER_ID) REFERENCES usuarios(USER_ID) ON DELETE CASCADE
);