USE peluqueria;

CREATE TABLE PERMISOS (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USER_ID VARCHAR(15) NOT NULL,
	TITLE VARCHAR(20) NOT NULL,
	URL VARCHAR(140) NOT NULL,
	MODULO_CREAR BOOL,
	MODULO_ELIMINAR BOOL,
	MODULO_MODIFICAR BOOL,
	MODULO_CONSULTAR BOOL,
	FOREIGN KEY(USER_ID) REFERENCES USUARIOS(USER_ID) ON DELETE CASCADE
);

insert into PERMISOS (USER_ID, TITLE, URL, MODULO_CREAR, MODULO_ELIMINAR, MODULO_MODIFICAR, MODULO_CONSULTAR)
			values ('rbalcaza', 'Clientes', 'Customers', 1, 1, 1, 1);
insert into PERMISOS (USER_ID, TITLE, URL, MODULO_CREAR, MODULO_ELIMINAR, MODULO_MODIFICAR, MODULO_CONSULTAR)
			values ('rbalcaza', 'Profesionales', 'Profesionals', 1, 1, 1, 1);
insert into PERMISOS (USER_ID, TITLE, URL, MODULO_CREAR, MODULO_ELIMINAR, MODULO_MODIFICAR, MODULO_CONSULTAR)
			values ('rbalcaza', 'Turnos', 'Turnos', 1, 1, 1, 1);
insert into PERMISOS (USER_ID, TITLE, URL, MODULO_CREAR, MODULO_ELIMINAR, MODULO_MODIFICAR, MODULO_CONSULTAR)
			values ('rbalcaza', 'Reporte', 'Reporte', 1, 1, 1, 1);