use peluqueria;

create table turnos (
		ID INT(7) NOT NULL AUTO_INCREMENT PRIMARY KEY,
		FECHA DATE NOT NULL,
		HORA TIME NOT NULL,
		ID_CLIENTE INT(5),
		ID_PROFESIONAL INT(5),
		DESCRIPCION VARCHAR (140),
		IMPORTE DECIMAL(9,2),
		PAGO DECIMAL(9,2),
		FOREIGN KEY (ID_CLIENTE) REFERENCES clientes(ID) ON DELETE SET NULL,
		FOREIGN KEY (ID_PROFESIONAL) REFERENCES profesionales(ID) ON DELETE SET NULL
);